version: '2'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    environment:
      TZ: Asia/Tokyo
      LANG: ja_JP.utf8
      LC_ALL: C

  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      TZ: Asia/Tokyo
      LANG: ja_JP.utf8
      LC_ALL: C
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: text:1:1,binary:1:1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

