grails:
    profile: base
    codegen:
        defaultPackage: kafka.sample
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

---
management:
  endpoints:
    enabled-by-default: true
  security:
    enabled: false

---
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: topic1
          contentType: text/plain
          #contentType: application/json
        output:
          destination: topic1
          contentType: text/plain
          #contentType: application/json
      kafka:
        binder:
          brokers: 127.0.0.1
          defaultBrokerPort: 9092
          zkNodes: 127.0.0.1
          defaultZkPort: 2181
          autoCreateTopics: false
