---
grails:
    profile: web
    codegen:
        defaultPackage: sample
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none

---
management:
  endpoints:
    enabled-by-default: true
  security:
    enabled: false

---
spring:
  cloud:
    stream:
      bindings:
        text-input:
          destination: text
          contentType: application/json
        text-output:
          destination: text
          contentType: application/json
        binary-input:
          destination: binary
          contentType: application/json
        binary-output:
          destination: binary
          contentType: application/json
      kafka:
        binder:
          brokers: 127.0.0.1
          defaultBrokerPort: 9092
          zkNodes: 127.0.0.1
          defaultZkPort: 2181
          autoCreateTopics: false

---
sample:
  binaryProducer:
    chunkSize: 1024     # bytes
    retryInterval: 1000 # msec
    retryMaxCount: 5    # times
  binaryConsumer:
    storeDir: build/tmp/storeDir
